##################################################################################################################
#                               Copyright 2024 Airbus UPNext OPTIMATE Demonstrator 
#
# This MSG File contains the definition of DecodedAdsbMessageList generated automatically by MATLAB script Generate_MSGFiles.m.
# System Composer MODEL File name: test.slx
# ModelInfo.BlockDiagramName: test
# ModelInfo.SimulinkVersion/ReleaseName: 10.6 / R2022b
# ModelInfo.ModelVersion: 1.5
# ModelInfo.LastModifiedBy: to41629
# Generation Date: 25-Mar-2024
##################################################################################################################

DecodedAdsbMessage[] messages
