##################################################################################################################
#                               Copyright 2024 Airbus UPNext OPTIMATE Demonstrator 
#
# This MSG File contains the definition of DecodedAdsbMessage generated automatically by MATLAB script Generate_MSGFiles.m.
# System Composer MODEL File name: test.slx
# ModelInfo.BlockDiagramName: test
# ModelInfo.SimulinkVersion/ReleaseName: 10.6 / R2022b
# ModelInfo.ModelVersion: 1.5
# ModelInfo.LastModifiedBy: to41629
# Generation Date: 25-Mar-2024
##################################################################################################################

int32 icaocode
float32 latitude
float32 longitude
float32 Altitude
float32 horizontal_velocity
float32 vertical_velocity
float32 track
int32 angle_type
int32 emitter_cat
string calsign
int32 nic
int32 nacp
int32 emergency_status
bool updated
